from manim import *
class countdown(Scene):
    def construct(self):
        r1 = Rectangle(height=0.5, width=0.5, color=BLUE_E, fill_opacity=0.9).move_to([-5, 0, 0])
        r2 = Rectangle(height=0.5, width=0.5, color=BLUE_B, fill_opacity=0.9).move_to([5, 0, 0])
        r3 = Rectangle(height=0.5, width=0.5, fill_opacity=0.9)
        r4 = Rectangle(height=0.5, width=0.5, fill_opacity=0.9)
        r5 = Rectangle(height=0.5, width=0.5, fill_opacity=0.9)
        r6 = Rectangle(height=0.5, width=0.5, fill_opacity=0.9)
        r7 = Rectangle(height=0.5, width=0.5, fill_opacity=0.9)
        g1 = VGroup(r1, r2)
        g2 = VGroup(r3, r4, r5, r6, r7)
        g2.arrange()
        g2.set_color_by_gradient(BLUE_E, BLUE_B)
        s1 = SurroundingRectangle(g2, color=WHITE)
        s2 = SurroundingRectangle(s1, color=WHITE)
        t1 = Text("2").next_to(r3, UP, buff = 0.5).scale(1.5)
        t2 = Text("8").next_to(r4, UP, buff = 0.5).scale(1.5)
        t3 = Text("9").next_to(r5, UP, buff = 0.5).scale(1.5)
        t4 = Text("8").next_to(r6, UP, buff = 0.5).scale(1.5)
        t5 = Text("0").next_to(r7, UP, buff = 0.5).scale(1.5)
        t6 = Text("Made by Prateep", color=BLUE_B)
        s3 = SurroundingRectangle(t6, color=WHITE)
        t = VGroup(t1, t2, t3, t4, t5)
        g3 = VGroup(t, g2, s1, s2)
        d = Rectangle(height=0.5, width=0.5, fill_opacity=0.8, color=WHITE)
        t7 = Text("69").next_to(r1, UP, buff = 0.5).scale(1.5)
        t8 = Text("420").next_to(r2, UP, buff = 0.5).scale(1.5)
        g4 = VGroup(g1, t7, t8)
        self.play(Write(g1))
        self.play(r1.animate.shift(RIGHT*4.75), r2.animate.shift(LEFT*4.75))
        self.wait(0.2)
        self.play(r1.animate.shift(LEFT*1.4), r2.animate.shift(RIGHT*1.4))
        self.play(Write(t7), Write(t8))
        self.play(ReplacementTransform(g4, g2))
        self.play(Write(s1), Write(s2), Write(t))
        self.play(Indicate(t1, color=BLUE_C), Indicate(r3, color=WHITE, scale_factor=0.5))
        self.play(Indicate(t2, color=BLUE_C), Indicate(r4, color=WHITE, scale_factor=0.5))
        self.play(Indicate(t3, color=BLUE_C), Indicate(r5, color=WHITE, scale_factor=0.5))
        self.play(Indicate(t4, color=BLUE_C), Indicate(r6, color=WHITE, scale_factor=0.5))
        self.play(Indicate(t5, color=BLUE_C), Indicate(r7, color=WHITE, scale_factor=0.5))
        self.play(g3.animate.scale(0.1))
        self.play(ReplacementTransform(g3, d), run_time = 1.5)
        self.play(d.animate.scale(150), run_time = 1.6)
        self.play(FadeOut(d, run_time = 2))
        self.play(Write(t6))
        self.wait(1)
        self.play(Write(s3, run_time = 0.3))
        self.wait(1)
